import React from 'react'
import { BOQItem } from '@/core/engine/boqCalculator'
import { generateShoppingList } from '@/core/engine/shoppingListGenerator'
import { Download, CheckCircle, Package } from 'lucide-react'
import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'

// New interfaces based on the provided diff
interface Story {
  id: string
  name: string
}

interface ShoppingListItem {
  name: string
  quantity: number
  unit: string
  location?: string // Added location
  category: string
  checked: boolean
}

interface ShoppingListProps {
  items: BOQItem[]
  projectName?: string
  stories?: Story[]
  projectId?: string
  isGroupedByStory?: boolean
}

export const ShoppingList: React.FC<ShoppingListProps> = ({ 
  items, 
  projectName = 'My Project',
  stories = [],
  projectId,
  isGroupedByStory = false
}) => {
  // Original phases generation
  const phases = generateShoppingList(items)

  // Use useMemo instead of useState + useEffect to avoid cascading renders
  const shoppingItems = React.useMemo(() => {
    // Strategy: 
    // If an item has a storyId, find its name.
    // If grouped -> We might need to split them if we want per-floor shopping.
    // OR we just list them: 
    // "Cement Brick | 5000 | Ground Floor"
    // "Cement Brick | 4000 | First Floor"
    
    const newItems = items.map(item => {
        let location = "General"
        if (item.storyName) location = item.storyName
        else if (item.storyId) {
            const s = stories.find(st => st.id === item.storyId)
            if (s) location = s.name
        } else if (stories.length > 0 && !item.storyId) {
             location = "Ground Floor" // Fallback
        }

        return {
            name: item.name || item.item,
            quantity: item.quantity,
            unit: item.unit,
            location: location,
            category: item.category,
            checked: false
        }
    })
    
    // Deduplication? 
    // If we want to merge:
    // We should merge only if name, unit AND location match.
    // If location differs, keep separate.
    
    const merged: ShoppingListItem[] = []
    newItems.forEach(item => {
        const existing = merged.find(m => m.name === item.name && m.unit === item.unit && m.location === item.location)
        if (existing) {
            existing.quantity += item.quantity
        } else {
            merged.push(item)
        }
    })

    return merged.sort((a,b) => a.category.localeCompare(b.category))
  }, [items, stories])

  const exportToPDF = () => {
    const doc = new jsPDF()
    
    // Header
    doc.setFontSize(20)
    doc.text('Shopping List', 14, 20)
    doc.setFontSize(12)
    doc.text(projectName, 14, 28)
    doc.setFontSize(10)
    doc.text(`Generated: ${new Date().toLocaleDateString()}`, 14, 34)
    
    let yPosition = 45

    // The diff suggests using shoppingItems for the PDF, not phases.
    // This implies a change in the PDF structure from phased to a single list.
    // I will follow the diff's instruction for the PDF table.

    // Single table for all shopping items
    doc.setFontSize(14)
    doc.setFont('helvetica', 'bold')
    doc.text('All Items', 14, yPosition) // Changed from phase.title to 'All Items'
    yPosition += 6
    
    doc.setFontSize(10)
    doc.setFont('helvetica', 'normal')
    doc.text('Consolidated list of all materials needed.', 14, yPosition) // Generic description
    yPosition += 8

    autoTable(doc, {
      startY: yPosition,
      head: [['Cat', 'Item', 'Qty', 'Unit', 'Location', 'Check']],
      body: shoppingItems.map(i => [
          i.category, 
          i.name, 
          i.quantity.toFixed(1), 
          i.unit, 
          i.location || '-', 
          '[ ]'
      ]),
      theme: 'grid',
      styles: { fontSize: 8 },
      headStyles: { fillColor: [41, 128, 185] },
      margin: { left: 14 },
    })

    yPosition = (doc as any).lastAutoTable.finalY + 10

    // Footer
    doc.setFontSize(8)
    doc.text('Generated by BuildSmart AI - buildsmart.ai', 14, 285)

    doc.save(`${projectName.replace(/\s+/g, '_')}_Shopping_List.pdf`)
  }

  return (
    <div className="bg-white rounded-lg shadow-lg p-6">
      <div className="flex items-center justify-between mb-6">
        <div>
          <h2 className="text-2xl font-bold text-slate-900 flex items-center gap-2">
            <Package size={28} className="text-blue-600" />
            Shopping List
          </h2>
          <p className="text-sm text-slate-600 mt-1">
            Phased purchasing guide for your project
          </p>
        </div>
        <button
          onClick={exportToPDF}
          className="flex items-center gap-2 bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 rounded-lg font-semibold transition-colors"
        >
          <Download size={20} />
          Export PDF
        </button>
      </div>

      {/* List Display */}
      <div className="space-y-6">
          <div className="border border-slate-200 rounded-lg overflow-hidden">
            <div className="p-4 bg-slate-50 border-b border-slate-200">
              <h3 className="text-lg font-bold text-slate-900">Consolidated List</h3>
            </div>

            <div className="p-4">
              <div className="space-y-2">
                {shoppingItems.map((item, index) => (
                  <div key={index} className="flex items-center justify-between py-2 border-b border-slate-100 last:border-0">
                    <div className="flex items-center gap-3">
                      <CheckCircle className="text-slate-400" size={18} />
                      <span className="font-medium text-slate-900">{item.name}</span>
                    </div>
                    <div className="text-right">
                      <span className="font-bold text-slate-900">
                        {item.quantity?.toFixed(2)}
                      </span>
                      <span className="text-xs font-semibold text-blue-600 bg-blue-50 px-2 py-0.5 rounded ml-2">
                        {item.unit}
                      </span>
                      {item.location && (
                          <span className="text-[10px] font-medium text-slate-500 bg-slate-100 px-1.5 py-0.5 rounded ml-2 border border-slate-200">
                              {item.location}
                          </span>
                      )}
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>
      </div>

      {/* Tips */}
      <div className="mt-6 bg-blue-50 border border-blue-200 rounded-lg p-4">
        <h4 className="font-semibold text-blue-900 mb-2">💡 Shopping Tips</h4>
        <ul className="text-sm text-blue-800 space-y-1">
          <li>• Buy Phase 1 materials before starting construction</li>
          <li>• Order Phase 2 materials when foundation is 80% complete</li>
          <li>• Order Phase 3 materials when walls are complete</li>
          <li>• Always add 5-10% extra for wastage</li>
        </ul>
      </div>
    </div>
  )
}


